### ISSUE TITLE
In games add view hitting Enter when filling location cancels form submission [bug]

### ISSUE THREAD

**Issue by Igonato** [goodfootclub/web#22]
Steps:
 - go to/games/add
 - start filling location name
 - select desired location from autocomplete suggestions with arrow keys
 - hit Enter

Form canceled...

Expected behavior: specific location selected

**Comment by bsko** [comment]
https://github.com/goodfootclub/web/commit/63fb9a9a3ee6579f9ab1ba5c6484f63e18ca8f62
